### ISSUE TITLE
Versão 2.0

### ISSUE THREAD

**Issue by cdias900** [eaemenkkstudios/overtracker-backend#2]
O que falta ser feito para lançar a versão 2.0

- [x] Migrar para a linguagem para TypeScript
- [x] Sistema de autenticação #3 
- [x] Migrar banco de dados do firebase para mongodb
- [x] Integrar contas com API OAuth da Blizzard
- [x] Chatbot com o DialogFlow #4 
- [x] ~Chat entre os usuários do app #5~
- [x] ~Apagar scores com mais de 2 meses~
